# Generated by Django 4.0.2 on 2023-04-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20211207_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
